spring:
  application:
    name: spring-boot-observability-study
  datasource:
    url: jdbc:h2:./app-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  metrics:
    tags:
      application: ${spring.application.name}
  
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% sampling for development, reduce it to <10% for production
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces