spring:
  application:
    name: observability-upstream-service
server:
  port: ${SERVER_PORT:8081}
downstream:
  url: ${DOWNSTREAM_URL}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  metrics:
    tags:
      application: ${spring.application.name}
  
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% sampling for development, reduce it to <10% for production

